services:
  - type: web
    name: rag-chatbot-backend
    env: docker
    rootCommand: ./
    plan: free
    branch: main
    repo: https://github.com/Sai-Pallav/Infosys-springboard-Internship
    envVars:
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: HF_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHON_PATH
        value: python3